import { contextBridge, ipcRenderer } from "electron";
import type {
  CancelExportRequest,
  ChromaNodeApi,
  ExportProgress,
  ExportProjectRequest,
  ExportSequenceRequest,
  ExportStillRequest,
  ExportSyntheticRequest,
  FrameExtractRequest,
  InstalledPack,
  LearningProgressPayload,
  LibraryAddRequest,
  LibraryDeleteRequest,
  LibraryDuplicateRequest,
  LibraryItem,
  LibraryToggleFavoriteRequest,
  LibraryUpdateRequest,
  PackExportRequest,
  PackImportRequest,
  ProbeMediaRequest,
  RelinkMediaRequest,
  SaveProjectRequest,
  VersionCreateRequest,
  VersionUpdateRequest,
  VersionDeleteRequest,
  VersionSwitchRequest,
  AnnotationCreateRequest,
  AnnotationUpdateRequest,
  AnnotationDeleteRequest,
  AnnotationListRequest,
  ReviewPackageExportRequest,
  ReviewPackageImportRequest,
  FeedbackImportRequest,
  FeedbackResolveRequest,
  HandoffPackageExportRequest,
  HandoffPackageImportRequest,
  HandoffPackageValidateRequest
} from "../shared/ipc.js";
import type { PackImportResult } from "../shared/pack.js";

const IpcChannel = {
  SelectMedia: "dialog:select-media",
  SaveProject: "project:save",
  OpenProject: "project:open",
  LoadProgress: "progress:load",
  SaveProgress: "progress:save",
  ResetProgress: "progress:reset",
  RelinkMedia: "media:relink",
  GetDiagnostics: "ffmpeg:get-diagnostics",
  ProbeMedia: "media:probe",
  ExtractFrame: "frame:extract",
  ExportSynthetic: "export:synthetic",
  ExportStill: "export:still",
  ExportSequence: "export:sequence",
  StartExport: "export:start",
  CancelExport: "export:cancel",
  ExportProgress: "export:progress",
  LibraryLoad: "library:load",
  LibrarySave: "library:save",
  LibraryAdd: "library:add",
  LibraryUpdate: "library:update",
  LibraryDelete: "library:delete",
  LibraryGet: "library:get",
  LibraryDuplicate: "library:duplicate",
  LibraryToggleFavorite: "library:toggle-favorite",
  PackExport: "pack:export",
  PackImport: "pack:import",
  PackList: "pack:list",
  PackUninstall: "pack:uninstall",
  VersionCreate: "review:version-create",
  VersionList: "review:version-list",
  VersionSwitch: "review:version-switch",
  VersionDelete: "review:version-delete",
  VersionUpdate: "review:version-update",
  AnnotationCreate: "review:annotation-create",
  AnnotationUpdate: "review:annotation-update",
  AnnotationDelete: "review:annotation-delete",
  AnnotationList: "review:annotation-list",
  ReviewPackageExport: "review:package-export",
  ReviewPackageImport: "review:package-import",
  FeedbackImport: "review:feedback-import",
  FeedbackResolve: "review:feedback-resolve",
  HandoffExport: "review:handoff-export",
  HandoffImport: "review:handoff-import",
  HandoffValidate: "review:handoff-validate"
} as const;

const api: ChromaNodeApi = {
  selectMedia: () => ipcRenderer.invoke(IpcChannel.SelectMedia),
  saveProject: (request: SaveProjectRequest) => ipcRenderer.invoke(IpcChannel.SaveProject, request),
  openProject: () => ipcRenderer.invoke(IpcChannel.OpenProject),
  loadProgress: () => ipcRenderer.invoke(IpcChannel.LoadProgress),
  saveProgress: (progress: LearningProgressPayload) => ipcRenderer.invoke(IpcChannel.SaveProgress, progress),
  resetProgress: () => ipcRenderer.invoke(IpcChannel.ResetProgress),
  relinkMedia: (request: RelinkMediaRequest) => ipcRenderer.invoke(IpcChannel.RelinkMedia, request),
  getDiagnostics: () => ipcRenderer.invoke(IpcChannel.GetDiagnostics),
  probeMedia: (request: ProbeMediaRequest) => ipcRenderer.invoke(IpcChannel.ProbeMedia, request),
  extractFrame: (request: FrameExtractRequest) => ipcRenderer.invoke(IpcChannel.ExtractFrame, request),
  exportSynthetic: (request?: ExportSyntheticRequest) => ipcRenderer.invoke(IpcChannel.ExportSynthetic, request),
  exportStill: (request: ExportStillRequest) => ipcRenderer.invoke(IpcChannel.ExportStill, request),
  exportSequence: (request: ExportSequenceRequest) => ipcRenderer.invoke(IpcChannel.ExportSequence, request),
  startExport: (request: ExportProjectRequest) => ipcRenderer.invoke(IpcChannel.StartExport, request),
  cancelExport: (request: CancelExportRequest) => ipcRenderer.invoke(IpcChannel.CancelExport, request),
  onExportProgress: (listener: (progress: ExportProgress) => void) => {
    const handler = (_event: Electron.IpcRendererEvent, progress: ExportProgress) => listener(progress);
    ipcRenderer.on(IpcChannel.ExportProgress, handler);
    return () => ipcRenderer.off(IpcChannel.ExportProgress, handler);
  },
  loadLibrary: () => ipcRenderer.invoke(IpcChannel.LibraryLoad),
  addLibraryItem: (request: LibraryAddRequest) => ipcRenderer.invoke(IpcChannel.LibraryAdd, request),
  updateLibraryItem: (request: LibraryUpdateRequest) => ipcRenderer.invoke(IpcChannel.LibraryUpdate, request),
  deleteLibraryItem: (request: LibraryDeleteRequest) => ipcRenderer.invoke(IpcChannel.LibraryDelete, request),
  getLibraryItem: (request: { id: string }) => ipcRenderer.invoke(IpcChannel.LibraryGet, request),
  duplicateLibraryItem: (request: LibraryDuplicateRequest) => ipcRenderer.invoke(IpcChannel.LibraryDuplicate, request),
  toggleLibraryItemFavorite: (request: LibraryToggleFavoriteRequest) => ipcRenderer.invoke(IpcChannel.LibraryToggleFavorite, request),
  exportPack: (request: PackExportRequest) => ipcRenderer.invoke(IpcChannel.PackExport, request),
  importPack: (request?: PackImportRequest) => ipcRenderer.invoke(IpcChannel.PackImport, request),
  getInstalledPacks: () => ipcRenderer.invoke(IpcChannel.PackList),
  uninstallPack: (request: { path: string }) => ipcRenderer.invoke(IpcChannel.PackUninstall, request),
  createVersion: (request: VersionCreateRequest) => ipcRenderer.invoke(IpcChannel.VersionCreate, request),
  listVersions: () => ipcRenderer.invoke(IpcChannel.VersionList),
  switchVersion: (request: VersionSwitchRequest) => ipcRenderer.invoke(IpcChannel.VersionSwitch, request),
  deleteVersion: (request: VersionDeleteRequest) => ipcRenderer.invoke(IpcChannel.VersionDelete, request),
  updateVersion: (request: VersionUpdateRequest) => ipcRenderer.invoke(IpcChannel.VersionUpdate, request),
  createAnnotation: (request: AnnotationCreateRequest) => ipcRenderer.invoke(IpcChannel.AnnotationCreate, request),
  updateAnnotation: (request: AnnotationUpdateRequest) => ipcRenderer.invoke(IpcChannel.AnnotationUpdate, request),
  deleteAnnotation: (request: AnnotationDeleteRequest) => ipcRenderer.invoke(IpcChannel.AnnotationDelete, request),
  listAnnotations: (request: AnnotationListRequest) => ipcRenderer.invoke(IpcChannel.AnnotationList, request),
  exportReviewPackage: (request: ReviewPackageExportRequest) => ipcRenderer.invoke(IpcChannel.ReviewPackageExport, request),
  importReviewPackage: (request: ReviewPackageImportRequest) => ipcRenderer.invoke(IpcChannel.ReviewPackageImport, request),
  importFeedback: (request: FeedbackImportRequest) => ipcRenderer.invoke(IpcChannel.FeedbackImport, request),
  resolveFeedback: (request: FeedbackResolveRequest) => ipcRenderer.invoke(IpcChannel.FeedbackResolve, request),
  exportHandoffPackage: (request: HandoffPackageExportRequest) => ipcRenderer.invoke(IpcChannel.HandoffExport, request),
  importHandoffPackage: (request: HandoffPackageImportRequest) => ipcRenderer.invoke(IpcChannel.HandoffImport, request),
  validateHandoffPackage: (request: HandoffPackageValidateRequest) => ipcRenderer.invoke(IpcChannel.HandoffValidate, request)
};

contextBridge.exposeInMainWorld("chromaNode", api);
