import { contextBridge, ipcRenderer } from "electron";
import type {
  CancelExportRequest,
  ChromaNodeApi,
  ExportProgress,
  ExportProjectRequest,
  ExportSequenceRequest,
  ExportStillRequest,
  ExportSyntheticRequest,
  FrameExtractRequest,
  InstalledPack,
  LearningProgressPayload,
  LibraryAddRequest,
  LibraryDeleteRequest,
  LibraryDuplicateRequest,
  LibraryItem,
  LibraryToggleFavoriteRequest,
  LibraryUpdateRequest,
  PackExportRequest,
  PackImportRequest,
  ProbeMediaRequest,
  RelinkMediaRequest,
  SaveProjectRequest,
  VersionCreateRequest,
  VersionUpdateRequest,
  VersionDeleteRequest,
  VersionSwitchRequest,
  AnnotationCreateRequest,
  AnnotationUpdateRequest,
  AnnotationDeleteRequest,
  AnnotationListRequest,
  ReviewPackageExportRequest,
  ReviewPackageImportRequest,
  FeedbackImportRequest,
  FeedbackResolveRequest,
  HandoffPackageExportRequest,
  HandoffPackageImportRequest,
  HandoffPackageValidateRequest
} from "../shared/ipc.js";
import type { PackImportResult } from "../shared/pack.js";
import type { EntitlementFlags } from "../shared/entitlement.js";
import type { TelemetryConsent } from "../shared/telemetry.js";
import type { FeedbackSubmission } from "../shared/support.js";
import type { UpdateChannel, ReleaseChannelConfig } from "../shared/update.js";
import type { PricingTier, OnboardingExperiment, LaunchMetrics } from "../shared/launchConfig.js";

const IpcChannel = {
  SelectMedia: "dialog:select-media",
  SaveProject: "project:save",
  OpenProject: "project:open",
  LoadProgress: "progress:load",
  SaveProgress: "progress:save",
  ResetProgress: "progress:reset",
  RelinkMedia: "media:relink",
  GetDiagnostics: "ffmpeg:get-diagnostics",
  ProbeMedia: "media:probe",
  ExtractFrame: "frame:extract",
  ExportSynthetic: "export:synthetic",
  ExportStill: "export:still",
  ExportSequence: "export:sequence",
  StartExport: "export:start",
  CancelExport: "export:cancel",
  ExportProgress: "export:progress",
  LibraryLoad: "library:load",
  LibrarySave: "library:save",
  LibraryAdd: "library:add",
  LibraryUpdate: "library:update",
  LibraryDelete: "library:delete",
  LibraryGet: "library:get",
  LibraryDuplicate: "library:duplicate",
  LibraryToggleFavorite: "library:toggle-favorite",
  PackExport: "pack:export",
  PackImport: "pack:import",
  PackList: "pack:list",
  PackUninstall: "pack:uninstall",
  VersionCreate: "review:version-create",
  VersionList: "review:version-list",
  VersionSwitch: "review:version-switch",
  VersionDelete: "review:version-delete",
  VersionUpdate: "review:version-update",
  AnnotationCreate: "review:annotation-create",
  AnnotationUpdate: "review:annotation-update",
  AnnotationDelete: "review:annotation-delete",
  AnnotationList: "review:annotation-list",
  ReviewPackageExport: "review:package-export",
  ReviewPackageImport: "review:package-import",
  FeedbackImport: "review:feedback-import",
  FeedbackResolve: "review:feedback-resolve",
  HandoffExport: "review:handoff-export",
  HandoffImport: "review:handoff-import",
  HandoffValidate: "review:handoff-validate",
  LicenseValidate: "license:validate",
  LicenseCheckFeature: "license:check-feature",
  LicenseStartTrial: "license:start-trial",
  LicenseActivate: "license:activate",
  LicenseDeactivate: "license:deactivate",
  LicenseGetState: "license:get-state",
  LicenseClear: "license:clear",
  TelemetryGetConsent: "telemetry:get-consent",
  TelemetrySetConsent: "telemetry:set-consent",
  TelemetryTrack: "telemetry:track",
  TelemetryFlush: "telemetry:flush",
  TelemetryDeleteAll: "telemetry:delete-all",
  TelemetryGetQueueSize: "telemetry:get-queue-size",
  CrashCapture: "support:capture-crash",
  GetAppDiagnostics: "app:get-diagnostics",
  CreateSupportBundle: "support:create-bundle",
  SubmitFeedback: "support:submit-feedback",
  UpdateCheck: "update:check",
  UpdateGetStatus: "update:get-status",
  UpdateGetConfig: "update:get-config",
  UpdateSetChannel: "update:set-channel",
  UpdateSetAutoCheck: "update:set-auto-check",
  UpdateGetChannels: "update:get-channels",
  LaunchGetPricingTiers: "launch:get-pricing-tiers",
  LaunchGetExperiments: "launch:get-experiments",
  LaunchGetMetrics: "launch:get-metrics",
  LaunchSetExperiment: "launch:set-experiment"
} as const;

const api: ChromaNodeApi = {
  selectMedia: () => ipcRenderer.invoke(IpcChannel.SelectMedia),
  saveProject: (request: SaveProjectRequest) => ipcRenderer.invoke(IpcChannel.SaveProject, request),
  openProject: () => ipcRenderer.invoke(IpcChannel.OpenProject),
  loadProgress: () => ipcRenderer.invoke(IpcChannel.LoadProgress),
  saveProgress: (progress: LearningProgressPayload) => ipcRenderer.invoke(IpcChannel.SaveProgress, progress),
  resetProgress: () => ipcRenderer.invoke(IpcChannel.ResetProgress),
  relinkMedia: (request: RelinkMediaRequest) => ipcRenderer.invoke(IpcChannel.RelinkMedia, request),
  getDiagnostics: () => ipcRenderer.invoke(IpcChannel.GetDiagnostics),
  probeMedia: (request: ProbeMediaRequest) => ipcRenderer.invoke(IpcChannel.ProbeMedia, request),
  extractFrame: (request: FrameExtractRequest) => ipcRenderer.invoke(IpcChannel.ExtractFrame, request),
  exportSynthetic: (request?: ExportSyntheticRequest) => ipcRenderer.invoke(IpcChannel.ExportSynthetic, request),
  exportStill: (request: ExportStillRequest) => ipcRenderer.invoke(IpcChannel.ExportStill, request),
  exportSequence: (request: ExportSequenceRequest) => ipcRenderer.invoke(IpcChannel.ExportSequence, request),
  startExport: (request: ExportProjectRequest) => ipcRenderer.invoke(IpcChannel.StartExport, request),
  cancelExport: (request: CancelExportRequest) => ipcRenderer.invoke(IpcChannel.CancelExport, request),
  onExportProgress: (listener: (progress: ExportProgress) => void) => {
    const handler = (_event: Electron.IpcRendererEvent, progress: ExportProgress) => listener(progress);
    ipcRenderer.on(IpcChannel.ExportProgress, handler);
    return () => ipcRenderer.off(IpcChannel.ExportProgress, handler);
  },
  loadLibrary: () => ipcRenderer.invoke(IpcChannel.LibraryLoad),
  addLibraryItem: (request: LibraryAddRequest) => ipcRenderer.invoke(IpcChannel.LibraryAdd, request),
  updateLibraryItem: (request: LibraryUpdateRequest) => ipcRenderer.invoke(IpcChannel.LibraryUpdate, request),
  deleteLibraryItem: (request: LibraryDeleteRequest) => ipcRenderer.invoke(IpcChannel.LibraryDelete, request),
  getLibraryItem: (request: { id: string }) => ipcRenderer.invoke(IpcChannel.LibraryGet, request),
  duplicateLibraryItem: (request: LibraryDuplicateRequest) => ipcRenderer.invoke(IpcChannel.LibraryDuplicate, request),
  toggleLibraryItemFavorite: (request: LibraryToggleFavoriteRequest) => ipcRenderer.invoke(IpcChannel.LibraryToggleFavorite, request),
  exportPack: (request: PackExportRequest) => ipcRenderer.invoke(IpcChannel.PackExport, request),
  importPack: (request?: PackImportRequest) => ipcRenderer.invoke(IpcChannel.PackImport, request),
  getInstalledPacks: () => ipcRenderer.invoke(IpcChannel.PackList),
  uninstallPack: (request: { path: string }) => ipcRenderer.invoke(IpcChannel.PackUninstall, request),
  createVersion: (request: VersionCreateRequest) => ipcRenderer.invoke(IpcChannel.VersionCreate, request),
  listVersions: () => ipcRenderer.invoke(IpcChannel.VersionList),
  switchVersion: (request: VersionSwitchRequest) => ipcRenderer.invoke(IpcChannel.VersionSwitch, request),
  deleteVersion: (request: VersionDeleteRequest) => ipcRenderer.invoke(IpcChannel.VersionDelete, request),
  updateVersion: (request: VersionUpdateRequest) => ipcRenderer.invoke(IpcChannel.VersionUpdate, request),
  createAnnotation: (request: AnnotationCreateRequest) => ipcRenderer.invoke(IpcChannel.AnnotationCreate, request),
  updateAnnotation: (request: AnnotationUpdateRequest) => ipcRenderer.invoke(IpcChannel.AnnotationUpdate, request),
  deleteAnnotation: (request: AnnotationDeleteRequest) => ipcRenderer.invoke(IpcChannel.AnnotationDelete, request),
  listAnnotations: (request: AnnotationListRequest) => ipcRenderer.invoke(IpcChannel.AnnotationList, request),
  exportReviewPackage: (request: ReviewPackageExportRequest) => ipcRenderer.invoke(IpcChannel.ReviewPackageExport, request),
  importReviewPackage: (request: ReviewPackageImportRequest) => ipcRenderer.invoke(IpcChannel.ReviewPackageImport, request),
  importFeedback: (request: FeedbackImportRequest) => ipcRenderer.invoke(IpcChannel.FeedbackImport, request),
  resolveFeedback: (request: FeedbackResolveRequest) => ipcRenderer.invoke(IpcChannel.FeedbackResolve, request),
  exportHandoffPackage: (request: HandoffPackageExportRequest) => ipcRenderer.invoke(IpcChannel.HandoffExport, request),
  importHandoffPackage: (request: HandoffPackageImportRequest) => ipcRenderer.invoke(IpcChannel.HandoffImport, request),
  validateHandoffPackage: (request: HandoffPackageValidateRequest) => ipcRenderer.invoke(IpcChannel.HandoffValidate, request),
  validateLicense: () => ipcRenderer.invoke(IpcChannel.LicenseValidate),
  checkFeatureEntitlement: (feature: keyof EntitlementFlags) => ipcRenderer.invoke(IpcChannel.LicenseCheckFeature, { feature }),
  startTrial: () => ipcRenderer.invoke(IpcChannel.LicenseStartTrial),
  activateLicense: (request: { licenseKey: string }) => ipcRenderer.invoke(IpcChannel.LicenseActivate, request),
  deactivateLicense: () => ipcRenderer.invoke(IpcChannel.LicenseDeactivate),
  getLicenseState: () => ipcRenderer.invoke(IpcChannel.LicenseGetState),
  clearLicense: () => ipcRenderer.invoke(IpcChannel.LicenseClear),
  getTelemetryConsent: () => ipcRenderer.invoke(IpcChannel.TelemetryGetConsent),
  setTelemetryConsent: (consent: TelemetryConsent) => ipcRenderer.invoke(IpcChannel.TelemetrySetConsent, consent),
  trackTelemetry: (request: { type: string; payload: Record<string, unknown> }) => ipcRenderer.invoke(IpcChannel.TelemetryTrack, request),
  flushTelemetry: () => ipcRenderer.invoke(IpcChannel.TelemetryFlush),
  deleteAllTelemetry: () => ipcRenderer.invoke(IpcChannel.TelemetryDeleteAll),
  getTelemetryQueueSize: () => ipcRenderer.invoke(IpcChannel.TelemetryGetQueueSize),
  captureCrash: (request: { crashType: string; message: string; stackTrace?: string; projectId?: string }) => ipcRenderer.invoke(IpcChannel.CrashCapture, request),
  getAppDiagnostics: () => ipcRenderer.invoke(IpcChannel.GetAppDiagnostics),
  createSupportBundle: (request: { includeLogs?: boolean; includeProjectDiagnostics?: boolean; includeMediaMetadata?: boolean; redactPaths?: boolean; contactInfo?: string }) => ipcRenderer.invoke(IpcChannel.CreateSupportBundle, request),
  submitFeedback: (request: FeedbackSubmission) => ipcRenderer.invoke(IpcChannel.SubmitFeedback, request),
  checkForUpdate: () => ipcRenderer.invoke(IpcChannel.UpdateCheck),
  getUpdateStatus: () => ipcRenderer.invoke(IpcChannel.UpdateGetStatus),
  getUpdateConfig: () => ipcRenderer.invoke(IpcChannel.UpdateGetConfig),
  setUpdateChannel: (channel: UpdateChannel) => ipcRenderer.invoke(IpcChannel.UpdateSetChannel, channel),
  setUpdateAutoCheck: (autoCheck: boolean) => ipcRenderer.invoke(IpcChannel.UpdateSetAutoCheck, autoCheck),
  getUpdateChannels: () => ipcRenderer.invoke(IpcChannel.UpdateGetChannels),
  getPricingTiers: () => ipcRenderer.invoke(IpcChannel.LaunchGetPricingTiers),
  getOnboardingExperiments: () => ipcRenderer.invoke(IpcChannel.LaunchGetExperiments),
  getLaunchMetrics: () => ipcRenderer.invoke(IpcChannel.LaunchGetMetrics),
  setOnboardingExperiment: (id: string, enabled: boolean) => ipcRenderer.invoke(IpcChannel.LaunchSetExperiment, { id, enabled })
};

contextBridge.exposeInMainWorld("chromaNode", api);
